# frozen_string_literal: true

source "https://rubygems.org"

gem 'ha2itat', path: "vendor/gems/ha2itat"

gem 'youtube-dl.rb'

gem "dry-types", "~> 1.0", ">= 1.6.1"
gem "puma"
gem "rake"

group :development, :test do
  gem "dotenv"
end

group :cli, :development do
  gem "hanami-reloader"
end

group :cli, :development, :test do
  gem "hanami-rspec"
end

group :development do
  gem "guard-puma", "~> 0.8"
end

group :test do
  gem "rack-test"
  gem 'guard'
end
