# frozen_string_literal: true

group :server do
  guard "puma", port: ENV.fetch("HANAMI_PORT", 2300) do
    watch(%r{^config/.+\.rb$})
    watch(%r{^app/.+\.rb$})
    watch(%r{^lib/.+\.rb$})
    watch(%r{vendor/gems/ha2itat/.+\.rb$})
    watch(%r{slices/.+\.rb$})
  end
end
